#!/usr/bin/env python3
# Builds Prover.toml witness data for the real-data Noir circuits
# (fba_protocol_real_quotes / fba_protocol_real_trades) from the real
# AAPL CSVs in ../data. Same derive()/cross-check logic as
# ~/zk_fba_noir/protocol_prover_gen.py (the synthetic-data version) --
# only Price/Bids++/Asks++ are trusted as input, everything else is
# recomputed here and cross-checked against the CSV's own precomputed
# columns before being written out.

import csv
import os

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "data")

def load_book(path):
    with open(path, newline="") as f:
        rows = list(csv.DictReader(f))
    prices = [int(r["Price"]) for r in rows]
    b = [int(r["Bids++"]) for r in rows]
    a = [int(r["Asks++"]) for r in rows]
    return prices, b, a, rows

def derive(b, a):
    n = len(b)
    acc_b = [0] * n
    acc_b[n - 1] = b[n - 1]
    for i in range(n - 2, -1, -1):
        acc_b[i] = acc_b[i + 1] + b[i]
    acc_a = [0] * n
    acc_a[0] = a[0]
    for i in range(1, n):
        acc_a[i] = acc_a[i - 1] + a[i]
    min_x = [min(acc_a[i], acc_b[i]) for i in range(n)]
    v_max = max(min_x)
    plateau_idx = [i for i in range(n) if min_x[i] == v_max]
    c, d = plateau_idx[0], plateau_idx[-1]
    assert plateau_idx == list(range(c, d + 1)), \
        "plateau is not contiguous -- Min(X) unimodality assumption violated"
    surp_b = [acc_b[i] - min_x[i] for i in range(n)]
    surp_a = [acc_a[i] - min_x[i] for i in range(n)]
    delta = [surp_a[i] + surp_b[i] for i in range(n)]
    v_min_delta = min(delta[i] for i in range(c, d + 1))
    p_star = next(i for i in range(c, d + 1) if delta[i] == v_min_delta)
    slack_l = (v_max - 1 - min_x[c - 1]) if c > 0 else 0
    slack_r = (v_max - 1 - min_x[d + 1]) if d < n - 1 else 0
    return {
        "n": n, "acc_b": acc_b, "acc_a": acc_a, "min_x": min_x,
        "v_max": v_max, "c": c, "d": d,
        "surp_b": surp_b, "surp_a": surp_a, "delta": delta,
        "v_min_delta": v_min_delta, "p_star": p_star,
        "slack_l": slack_l, "slack_r": slack_r,
    }

def cross_check(rows, der):
    n = der["n"]
    errs = []
    for i, r in enumerate(rows):
        if int(r["Bid_Depth"]) != der["acc_b"][i]: errs.append(f"row {i}: Bid_Depth mismatch")
        if int(r["Ask_Depth"]) != der["acc_a"][i]: errs.append(f"row {i}: Ask_Depth mismatch")
        if int(r["Min_Bid_Ask"]) != der["min_x"][i]: errs.append(f"row {i}: Min_Bid_Ask mismatch")
        if int(r["Bid_Surplus"]) != der["surp_b"][i]: errs.append(f"row {i}: Bid_Surplus mismatch")
        if int(r["Ask_Surplus"]) != der["surp_a"][i]: errs.append(f"row {i}: Ask_Surplus mismatch")
        if int(r["Abs_Delta"]) != der["delta"][i]: errs.append(f"row {i}: Abs_Delta mismatch")
    csv_mcv = int(rows[0]["MCV"])
    if csv_mcv != der["v_max"]:
        errs.append(f"V_max mismatch: derived {der['v_max']} vs CSV MCV {csv_mcv}")
    if errs:
        raise AssertionError(f"{len(errs)} cross-check mismatches, e.g.: {errs[:5]}")
    print(f"  cross-check OK against CSV precomputed columns ({n} rows)")

def toml_array(name, values):
    return f"{name} = [{', '.join(str(v) for v in values)}]\n"

def write_prover_toml(path, b, a, der):
    n = der["n"]
    with open(path, "w") as f:
        f.write(f"# Auto-generated by gen_provers.py -- n={n} real AAPL ticks\n")
        f.write(toml_array("b", b))
        f.write(toml_array("a", a))
        f.write(toml_array("acc_b", der["acc_b"]))
        f.write(toml_array("acc_a", der["acc_a"]))
        f.write(toml_array("min_x", der["min_x"]))
        f.write(toml_array("surp_b", der["surp_b"]))
        f.write(toml_array("surp_a", der["surp_a"]))
        f.write(toml_array("delta", der["delta"]))
        f.write(f"slack_l = {der['slack_l']}\n")
        f.write(f"slack_r = {der['slack_r']}\n")
        f.write(f"v_max = {der['v_max']}\n")
        f.write(f"v_min_delta = {der['v_min_delta']}\n")
        f.write(f"c = {der['c']}\n")
        f.write(f"d = {der['d']}\n")
        f.write(f"p_star = {der['p_star']}\n")

def main():
    jobs = [
        (os.path.join(DATA, "order_book_real_quotes_100.csv"),
         os.path.join(HERE, "fba_protocol_real_quotes", "Prover.toml")),
        (os.path.join(DATA, "order_book_real_trades_100.csv"),
         os.path.join(HERE, "fba_protocol_real_trades", "Prover.toml")),
    ]
    for csv_path, out_path in jobs:
        print(f"[{csv_path}]")
        prices, b, a, rows = load_book(csv_path)
        der = derive(b, a)
        cross_check(rows, der)
        print(f"  n={der['n']}  V_max={der['v_max']}  c={der['c']}  d={der['d']}  "
              f"V_min_delta={der['v_min_delta']}  p*={der['p_star']}")
        write_prover_toml(out_path, b, a, der)
        print(f"  wrote {out_path}\n")

if __name__ == "__main__":
    main()
